name = "Tentacle Flavoured"
author = "Octelly"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a422f899e5c8946432b507926bd57876667d6fdebc2624f166f015744451b6b7"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
