name = "Tentacle Flavoured"
author = "Octelly"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cedc51a4538777d183e4cb36493f5d4ce2be77587e093b35a5b05ee8fdf1ce34"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
