name = "Tentacle Flavoured"
author = "Octelly"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c08c5249431a945db7ebad1f4950c842a19106730093625aac3eb3ed08282691"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
